### PR TITLE
fix: close #110; shutdown additional thread pools right now when broker is in shutdown

### LINKED ISSUE #110: FETCH_RETRY_SCHEDULER stops Kafka broker from shutting down
server.log: 
```
[2023-08-28 04:14:02,207] INFO [BrokerLifecycleManager id=3] Transitioning from PENDING_CONTROLLED_SHUTDOWN to SHUTTING_DOWN. (kafka.server.BrokerLifecycleManager)
[2023-08-28 04:14:02,208] INFO [BrokerToControllerChannelManager broker=3 name=heartbeat]: Shutting down (kafka.server.BrokerToControllerRequestThread)
[2023-08-28 04:14:02,209] INFO [BrokerToControllerChannelManager broker=3 name=heartbeat]: Shutdown completed (kafka.server.BrokerToControllerRequestThread)
[2023-08-28 04:14:02,209] INFO [BrokerToControllerChannelManager broker=3 name=heartbeat]: Stopped (kafka.server.BrokerToControllerRequestThread)
[2023-08-28 04:14:02,210] INFO [SocketServer listenerType=BROKER, nodeId=3] Stopping socket server request processors (kafka.network.SocketServer)
[2023-08-28 04:14:02,219] INFO [BrokerMetadataListener id=3] Not processing HandleCommitsEvent because the event queue is closed. (kafka.server.metadata.BrokerMetadataListener)
[2023-08-28 04:14:02,220] INFO Broker to controller channel manager for heartbeat shutdown (kafka.server.BrokerToControllerChannelManagerImpl)
[2023-08-28 04:14:02,224] INFO [SocketServer listenerType=BROKER, nodeId=3] Stopped socket server request processors (kafka.network.SocketServer)
[2023-08-28 04:14:02,225] INFO [data-plane Kafka Request Handler on Broker 3], shutting down (kafka.server.KafkaRequestHandlerPool)
[2023-08-28 04:14:02,464] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:05,466] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:08,468] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:11,469] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:14,470] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:17,472] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:20,473] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:23,475] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:26,187] INFO [LocalLog partition=__cluster_metadata-0, dir=/mnt/kafka/kafka-metadata-logs] Rolled new log segment at offset 597 in 1 ms. (kafka.log.LocalLog)
[2023-08-28 04:14:26,197] INFO [ProducerStateManager partition=__cluster_metadata-0] Wrote producer snapshot at offset 597 with 0 producer ids in 11 ms. (kafka.log.ProducerStateManager)
[2023-08-28 04:14:26,476] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:29,478] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:32,480] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:35,481] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
[2023-08-28 04:14:38,483] ERROR Fetch stream[3980] [756,768) fail, retry later (kafka.log.es.AlwaysSuccessClient)
```

### PR DESCRIPTION
**Pull request by mooc9988**

### CODE REVIEW

File: core/src/main/scala/kafka/server/ReplicaManager.scala [hunk 1]
```diff
@@ -2341,4 +2341,9 @@ class ReplicaManager(val config: KafkaConfig,
       }
     }
   }
+
+  def shutdownAdditionalThreadPools(): Unit = {
```
Comment (superhx) [inline core/src/main/scala/kafka/server/ReplicaManager.scala:2345]: replicaManager has a shutdown method

Comment (mooc9988) [reply core/src/main/scala/kafka/server/ReplicaManager.scala:2345]: The shutdown of logManager is later than that of replicaManager. To make sure all opened partitions have all been closed in the shutdown of logManager, these thread pools should be shut down here.  The final order is replicaManager.shutdown() > logManager.shutdown() > additional thread pools shut down.

**Review by superhx — APPROVED** [review]
